log_level: debug

# 41238 is the evm chain id for Andromeda network
#evm_rpc: wss://evm-rpc-ws-andromeda.galactica.com
evm_rpc: https://evm-rpc-http-andromeda.galactica.com

db_backend: pebbledb

grpc:
  address: localhost:50651

grpc_gateway:
  address: localhost:8480

indexer:
  # The indexer mode can be either "poll" or "ws"
  mode: poll

  # The polling interval for the indexer when indexer mode is "poll"
  polling_interval: 1s

  # The maximum number of historical blocks to fetch from the indexer
  max_blocks_distance: 1000

  # The maximum channel size for the logs from websocket
  sink_channel_size: 100

  # Duration to log the progress of the indexer when indexer mode is "ws"
  sink_progress_tick: 10s

# You can specify multiple contracts to watch
zk_certificate_registry:
  - 0x454d8a0B2abdc7bAfef7FCbfb6B4c538c6F11C3b
