log_level: debug

# TODO: support multiple endpoints
evm_rpc: wss://evm-rpc-ws-reticulum.galactica.com

db_backend: pebbledb

grpc:
  address: localhost:50651

grpc_gateway:
  address: localhost:8480

indexer:
  max_blocks_distance: 1000
  sink_channel_size: 100
  sink_progress_tick: 5s

# You can specify multiple contracts to watch
zk_certificate_registry:
  - 0xbc196948e8c1Bc416aEaCf309a63DCEFfdf0cE31

