log_level: debug

evm_rpc: wss://galactica-mainnet.g.alchemy.com/public

db_backend: pebbledb

grpc:
  address: localhost:50651

grpc_gateway:
  address: localhost:8480

indexer:
  # The indexer mode can be either "poll" or "ws"
  mode: ws

  # The polling interval for the indexer when indexer mode is "poll"
  polling_interval: 1s

  # The maximum number of historical blocks to fetch from the indexer
  max_blocks_distance: 1000

  # The maximum channel size for the logs from websocket
  sink_channel_size: 100

  # Duration to log the progress of the indexer when indexer mode is "ws"
  sink_progress_tick: 10s

# V1 contracts (direct add/revoke)
zk_certificate_registry: []
# V2 contracts (queue-based processing)
zk_certificate_registry_v2:
  - address: 0xf98E14C33c573c26Bb14d8ca71e1c8756727Be53 # kyc
    start_block: 25600
  - address: 0xdD826498E46cb32259FDfb446965Ea734c5E28b7 # data
    start_block: 25600
  - address: 0x721aB287a601EB7D115000880CC219d7EEF93eAD # dex
    start_block: 25600
  - address: 0xb1124b8736520F58b80107c3DBB9B6c6512ad43b # gip6
    start_block: 25600
  - address: 0xb8c2d372f98AC4083a4114490051f341291b656f # gip7
    start_block: 25600
  - address: 0xaEae442A652aE8752d8BDA84A2Ba47711671F408 # rey
    start_block: 25600
  - address: 0xa931b18407A970BD28c42c7B668A312A88aEfF5d # twitter
    start_block: 25600
