log_level: debug

evm_rpc: wss://galactica-mainnet.g.alchemy.com/public

db_backend: pebbledb

grpc:
  address: localhost:50651

grpc_gateway:
  address: localhost:8480

indexer:
  # The indexer mode can be either "poll" or "ws"
  mode: ws

  # The polling interval for the indexer when indexer mode is "poll"
  polling_interval: 1s

  # The maximum number of historical blocks to fetch from the indexer
  max_blocks_distance: 1000

  # The maximum channel size for the logs from websocket
  sink_channel_size: 100

  # Duration to log the progress of the indexer when indexer mode is "ws"
  sink_progress_tick: 10s

# V1 contracts (direct add/revoke)
zk_certificate_registry: []
# V2 contracts (queue-based processing)
zk_certificate_registry_v2:
  - address: 0x5fce9D01Fa2f65fF17C3678c7970b8986e9270e4 # kyc
    start_block: 26000
  - address: 0x7bBC71FF2b1e46B30d5C6Fa20C88DA8F1C41a5E7 # data
    start_block: 26000
  - address: 0x2E994DC599847c1dFf9E162164d2532ACe5CF920 # dex
    start_block: 26000
  - address: 0x0acd2c41496d821683F2a3449F73863D2e3734E6 # gip6
    start_block: 26000
  - address: 0x81c7e95065a84dF098eDB4790Bb965FB60b60a66 # gip7
    start_block: 26000
  - address: 0x1d1B46e0fBD39DD5C37F5f21002f48310F93b89F # rey
    start_block: 26000
  - address: 0xAEb3403CAecc610be3130C8d6c152F472677514f # twitter
    start_block: 26000
