log_level: debug

evm_rpc: https://galactica-cassiopeia.explorer.alchemy.com/api

db_backend: pebbledb

grpc:
  address: localhost:50653

grpc_gateway:
  address: localhost:8483

indexer:
  # The indexer mode can be either "poll" or "ws"
  mode: poll

  # The polling interval for the indexer when indexer mode is "poll"
  polling_interval: 1s

  # The maximum number of historical blocks to fetch from the indexer
  max_blocks_distance: 1000

  # The maximum channel size for the logs from websocket
  sink_channel_size: 100

  # Duration to log the progress of the indexer when indexer mode is "ws"
  sink_progress_tick: 10s

# You can specify multiple contracts to watch
zk_certificate_registry:
  - 0x466bF1463F380C903CA69C2FeEF419824D8eA4d7 # kyc guardian_registry
