name: CICD

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  deploy:
    strategy:
      matrix:
        # ./config/merkle-{{ number }}.yaml
        chain:
          - "41238"
          - "9302"
          - "843843"
    runs-on: runtime
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          make build-linux DB_BACKEND=pebbledb BINARY_NAME=galacticad-merkle-${{ matrix.chain }}
          cp -f ./build/galacticad-merkle-${{ matrix.chain }} ${HOME}/go/bin/galacticad-merkle-${{ matrix.chain }}
          mkdir -p ${HOME}/galacticad-merkle-${{ matrix.chain }}
          cp -f ./config/merkle-${{ matrix.chain }}.yaml ${HOME}/galacticad-merkle-${{ matrix.chain }}/merkle-${{ matrix.chain }}.yaml
          systemctl --user enable gala-merkle@${{ matrix.chain }}
          systemctl --user restart gala-merkle@${{ matrix.chain }}
      - uses: eviden-actions/clean-self-hosted-runner@v1
        if: ${{ always() }}
